# Change these first
owner: cristix415
repo: uptime

# Forțează verificarea la 1 minut
workflow-schedule:
  uptime: "*/1 * * * *"

sites:
  - name: Bedstyle
    url: https://www.bedstyle.ro
  - name: Smartstyle
    url: https://smartstyle.ro

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Server
  introTitle: "Monitorizare Serverele Mele"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/cristix415/uptime

# NOTIFICĂRI TELEGRAM (Adaugă asta neapărat aici)
notifications:
  - type: telegram
    payload:
      token: "$TELEGRAM_BOT_TOKEN"
      chatId: "$TELEGRAM_CHAT_ID"
